apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres-app
  name: postgres-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-app
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose/kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: postgres-app
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_PASSWORD
              value: intelliqit
            - name: POSTGRES_USER
              value: myuser
          image: postgres
          name: postgres-app
      restartPolicy: Always
