apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: redis-app
  name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-app
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose/kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: redis-app
    spec:
      containers:
        - image: redis
          name: redis-app
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
