apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: result-app
  name: result-app
spec:
  ports:
    - name: "6060"
      port: 6060
      targetPort: 80
  selector:
    io.kompose.service: result-app
