apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: voting-app
  name: voting-app
spec:
  ports:
    - name: "5050"
      port: 5050
      targetPort: 80
  selector:
    io.kompose.service: voting-app
