apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose/kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: worker-app
  name: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker-app
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose/kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: worker-app
    spec:
      containers:
        - image: dockersamples/examplevotingapp_worker
          name: worker-app
      restartPolicy: Always
