---
apiVersion: v1
kind: Pod
metadata:
 name: mysql-pod
 labels:
  app: db
spec:
  containers:
   - name: mydb
     image: mysql
     env:
      - name: MYSQL_ROOT_PASSWORD
        value: intelliqit
     volumeMounts:
      - name: mysql-volume
        mountPath: /var/lib/mysql
     resources:
      requests:
       ephemeral-storage: 2Gi
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: new-pvc
... 
